- name: Creating directory to download Jdk binaries
    file:
      path: /opt/java/
      state: directory
      mode: "u=rw,g=wx,o=rwx"
      recurse: yes

- name: Download java binary from Oracle site
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
    dest: /opt/java/
    force_basic_auth: yes
    
- name: Unarchive tar file
  unarchive:
    src: /opt/java/jdk-8u161-linux-x64.tar.gz
    dest: /opt/java/jdk-8u161-linux-x64
    remote_src: yes
    
- name: Set Java HOME
  lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'>
                 line="export JAVA_HOME=/opt/java/jdk-8u161-linux-x64/"

- name: Set JAVA PATH
  lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'>
                 line="export PATH=$M2:$PATH:/opt/java/jdk-8u161-linux-x64/bin"

- name: Source Bashrc
  action: shell source ~/.bashrc
    
- name: Get Java version
    shell: java -version |& awk -F'"' '{print $2}'
    register: java_version

  - debug: msg="{{ java_version.stdout_lines }}"