- name: Creating directory to download Jdk binaries
    file:
      path: {{ installation_directory }}
      state: directory
      mode: "u=rw,g=wx,o=rwx"
      recurse: yes

- name: Download java binary from Oracle site
  get_url:
    url: {{ download_url }}
    dest: {{ installation_directory }}
    force_basic_auth: yes
    
- name: Unarchive tar file
  unarchive:
    src: {{ installation_directory }}/jdk-8u161-linux-x64.tar.gz
    dest: {{ installation_directory }}/jdk-8u161-linux-x64
    remote_src: yes
    
- name: Set Java HOME
  lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'>
                 line="export JAVA_HOME={{ installation_directory }}/jdk-8u161-linux-x64/"

- name: Set JAVA PATH
  lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'>
                 line="export PATH=$M2:$PATH:{{ installation_directory }}/jdk-8u161-linux-x64/bin"

- name: Source Bashrc
  action: shell source ~/.bashrc
    
- name: Get Java version
    shell: java -version |& awk -F'"' '{print $2}'
    register: java_version

  - debug: msg="{{ java_version.stdout_lines }}"