---
- hosts: azure_vms
  gather_facts: false
  remote_user: root
  sudo: yes
  vars_files:
    - ../vars/main.yml
  tasks:
    - maven_artifact:
        group_id: POC4-TEAM1
        artifact_id: InformationCentre
        extension: war
        repository_url: 'http://52.173.28.7:8081/repository/maven-releases/'
        username: build_user
        password: build_pwd
        dest: /opt/tomcat/webapps/InformationCentre.war
        version: latest
