---
- hosts: azure_vms
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Wait for SSH to come up
      wait_for:
        port: 22
        timeout: 2000
        state: started
    - name: echo the hostname of the vm
      shell: hostname
